### ISSUE TITLE
Feature requests (Rollup)

### ISSUE THREAD

**Issue by giancarlocp** [highmountaintea/create-mithril-app#2]
Really this is not a feature request, is a recommendation (second order) to bear in mind Rollup.
As a beginner this tool (CMA) is appreciated, and learning JS ecosystem is a little confusing, so i try to standing on the shoulders of giants. It is a suggestion based on [these 4 interviews](https://carlmungazi.github.io/sourcecodeadventures/) by @CarlMungazi, where 3 of them (@barneycarroll @tivac @orbitbot) use rollup, and the other (@porsager) has not delivered an opinion on them.

I also recommend [this article](https://medium.com/jsdownunder/rollup-vs-webpack-javascript-bundling-in-2018-b35758a2268), where he argues that rollup is simpler and as powerful as webpack after the last updates (code splitting).

Rollup seems to have Mithril's philosophy, simple and effective.

PD: i did not find a way to contact you.

**Comment by barneycarroll** [comment]
I like Rollup a lot more than Webpack. Webpack requires a lot of boilerplate to do the bare minimum, and the documentation makes it hard to understand the basics. Rollup on the other hand has a relatively fragmented documentation and maintenance has been a bit flaky recently. 

Of late I've started using Parcel and enjoyed it. It does a lot out of the box workout configuration, but on the other hand it's difficult to control exactly what and how it does.

**Comment by giancarlocp** [comment]
I have found 2 examples.
The fist from [@ArthurClemens](https://github.com/ArthurClemens/mithril-starter-rollup).
The last from [@porsager](https://github.com/porsager/BoilerWebApp).

**Comment by highmountaintea** [comment]
Thanks for the recommendation. I looked into Rollup initially, and I wasn't sure whether it would have all the features I need out of it (specifically producing ES5 compatible code for production). I will look at it again.

**Comment by highmountaintea** [comment]
I just revisited Rollup. Still not sure if it has all the features I need yet. I'll close this request for now. Let's revisit this topic a few months down the line.
